### ISSUE TITLE
Britton's contributions

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt-3.0-paper#2]
I'm willing to contribute text to any of the following sections:
- Governance
- Processing and Analysis of Data
- Halo-Finding and Catalogs
- Scaling and Parallelism
- Analysis Modules

**Comment by ngoldbaum** [comment]
Can you also add yourself to the `content/metadata.yaml` file?

**Comment by MatthewTurk** [comment]
I've created issues for these: #8, #9, #10, #11, and #12
